spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j2303?useSSL=false&serveTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    username: 877058128@qq.com
    password: wbpinybnfrhubbhi
    host: smtp.qq.com
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.bootair.entity
  configuration:
    map-underscore-to-camel-case: true
